### ISSUE TITLE
Elberfelder 1871: Buch 41 (Markus) - Digitalisierung

### ISSUE THREAD

**Issue by maco-sf** [freie-bibel/freie-bibel#2]
Digitalisierung Markus der Elberfelder 1871.

**Comment by skreutzer** [comment]
Das hier ist nicht der richtige Ort, um die Aufgaben für ein anderes Repository zu verwalten, solange du nicht in unser Repository pushst – siehe stattdessen [hier](http://sourceforge.net/p/bibleworkplace/tickets/).
